# Generated by Django 3.0.7 on 2020-07-02 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_type', models.CharField(choices=[('own', 'own'), ('vallet', 'vallet')], max_length=10)),
                ('charge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'car'), ('bike', 'bike')], max_length=100)),
                ('charge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ParkingTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_slot', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=10)),
                ('entry_time', models.DateTimeField(blank=True)),
                ('disabled', models.BooleanField(default=False)),
                ('exit_time', models.DateTimeField(null=True)),
                ('driver_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parking_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ParkingTypeModel')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.VehicleTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(choices=[('driver', 'driver'), ('police', 'police'), ('security', 'security'), ('owner', 'owner')], max_length=100)),
                ('parking_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ParkingTypeModel')),
                ('slot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ParkingSlotModel')),
            ],
        ),
    ]
