# Generated by Django 3.0.7 on 2020-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodel',
            name='exit_time',
            field=models.DateTimeField(default=None),
        ),
    ]
