# Generated by Django 3.0.7 on 2020-07-02 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodel',
            name='entry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
