# Generated by Django 3.0.8 on 2020-07-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslotmodel',
            name='vehicle_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.VehicleInformationModel'),
        ),
    ]
