# Generated by Django 3.0.7 on 2020-07-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200702_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodel',
            name='entry_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
