# Generated by Django 3.0.8 on 2020-07-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        ('main', '0002_auto_20200711_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslotmodel',
            name='vehicle_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.VehicleInformationModel'),
        ),
    ]
