# Generated by Django 3.0.7 on 2020-07-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200701_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodel',
            name='exit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
