# Generated by Django 3.0.8 on 2020-07-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200712_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglotmodel',
            name='slots_in_floor',
        ),
    ]
