# Generated by Django 3.0.8 on 2020-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('vehicle_number_plate', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('vehicle_owner', models.CharField(max_length=100)),
                ('vehicle_owner_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
