# Generated by Django 3.0.7 on 2020-06-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
