# Generated by Django 3.0.7 on 2020-06-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200621_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
