# Generated by Django 3.0.7 on 2020-06-23 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200622_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='password2',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
