# Generated by Django 3.0.7 on 2020-06-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_registermodel_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='confirm',
            new_name='is_verified',
        ),
    ]
