# Generated by Django 3.0.7 on 2020-06-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_registerserializer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterSerializer',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='first_name',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='last_name',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='password',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='is_verified',
        ),
    ]
