# Generated by Django 3.0.7 on 2020-06-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200622_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterModel',
        ),
    ]
