version: '3'

services:
  db:
    image: mysql:5.7
    ports:
       - '3306:3306'
    environment:
      MYSQL_DATABASE: "parkinglot"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - "/home/ubuntu/db/init.sql:/init"
      - "/home/ubuntu/db/dbdata:/var/lib/mysql"
    restart: always


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
     image: redis:latest
     ports:
       - '6379:6379'
  web:
    build: "."
    command:
      bash -c "sleep 20; cd ParkingLot
      &&  python3 manage.py makemigrations
      && python3 manage.py migrate
      && (nohup celery -A ParkingLot worker &)
      && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - redis
    restart: always

