services:
  db:
    image: mysql:5.7
    environment:
      DATABASE_NAME: "parkinglot"
      DATABASE_PASSWORD: "1234"
      DATABASE_PORT: "3306"
      DATABASE_USER: "root"

  web:
    build: "."
    command: "python ParkingLot/ParkingLot/manage.py runserver"
    volumes:
      - ".:/app"
    ports: 
      - "8000:8000"
    depends_on:
      - db
