version: '3'
services:
    'db':
        image: 'mysql:5.7'
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: "book_store"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "1234"
            MYSQL_ROOT_PASSWORD: "1234"
        volumes:
            - "/home/ubuntu/db/dump:/docker-entrypoint-initdb.d"
            - "/home/ubuntu/db/dbdata:/var/lib/mysql"

    'rabbitmq':
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"

    'redis':
        image: redis:latest
        ports:
            - '6379:6379'

    'book_store':
        build: .
        command:
            bash -c "sleep 20; cd bookstore
            && python3 manage.py makemigrations
            && python3 manage.py migrate
            && (celery -A bookstore worker &)
            && (python3 manage.py runserver 0.0.0.0:8000 ) "
        volumes:
            - ".:/app"
        ports:
            - "8000:8000"
        depends_on:
            - db
            - rabbitmq
            -  redis