version: '3'

services:
  db:
    image: mysql:5.7
    ports:
       - '3306:3306'
    environment:
      MYSQL_DATABASE: "parkinglot"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - "/home/ubuntu/db/init.sql:/init"
      - "/home/ubuntu/db/dbdata:/var/lib/mysql"
    restart: always
  web:
    build: "."
    command: bash -c "python3 ParkingLot/manage.py makemigrations && python3 ParkingLot/manage.py migrate && python3 ParkingLot/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
  rabbitmq:
    image: rabbitmq:latest
    command: bash -c "rabbitmq-server && cd ParkingLot && celery -A ParkingLot worker - info"
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
     image: redis:latest
     ports:
       - '6379:6379'
